
platform :ios, '7.0'

inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'



target 'MoreStrictMVC' do
    
    pod 'SDWebImage' , '~>3.8.1'
    pod 'AFNetworking', '~> 3.0'
    pod 'MJRefresh','~> 3.1'
    pod 'MJExtension' , '~>3.0'
    pod 'SDAutoLayout', '~> 2.1.7'
    pod 'UITableView+FDTemplateLayoutCell' , '~> 1.5.beta'
    pod 'MBProgressHUD'

end
