
platform :ios, '7.0'

inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'



target 'moreStrictMVC' do
    
    
    pod 'AFOnoResponseSerializer' , '~>1.0.0'
    pod 'SDWebImage' , '~>3.8.1'
    pod 'SSKeychain'
    pod 'GPUImage'
    pod 'MBProgressHUD' , '~> 1.0.0'
    pod 'RESideMenu'
    pod 'GRMustache'
    pod 'MJRefresh' , '~>3.1.10'
    pod 'TBXML'
    pod 'DateTools'
    pod 'MJExtension' , '~>3.0.11'
    pod 'Myhpple'

end
